window.portfolioMedia = {
    "animation":  [
                      "Animation Reel 2020.mp4",
                      "ENA Voice Claim - Fish, Insecure \u0026 Wormaniac.mp4",
                      "If We Were Birds - Philomela\u0027s Trauma.mp4",
                      "If We Were Birds - Procne\u0027s Dilema.mp4",
                      "ONEYTROUSLE.mov",
                      "PillowMan - The AppleMen.mp4",
                      "PillowMan - The Little Green Pig.mp4",
                      "PillowMan - The PillowMan.mp4",
                      "PillowMan - The Three Gibbits.mp4",
                      "PillowMan - Town On The River.mp4",
                      "REAL AMOGUS CAUGHT ON TAPE BEING KILLED VIOLENTLY BY A TRAIN _NOT CLICKBATE_.mp4",
                      "woah metal pipe.mp4",
                      "Zach\u0027s Medical Record - Oney Plays Animated.mp4"
                  ],
    "copracorn":  [
                      "COPRACORN - a play by Kieran Potter (original cast 2025).mp4",
                      "copracorn bologna selfie final transparent.png",
                      "Copracorn Poster.jpg",
                      "copracorn shirt.png"
                  ],
    "daily-pokemon":  [
                          "0001 Bulbasaur - japanese ink wash.jpg",
                          "0002 Ivysaur - MARIO PAINT.JPG",
                          "0003 Venusaur - HEAVY PAINT.JPG",
                          "0004 Charrmander - owl house.jpg",
                          "0005 Charmeleon - rick and morty.jpg",
                          "0006 Charizard - Studio Ghibli CALCIFER.jpg",
                          "0007 Squirtle - Ren and Stimpy.jpg",
                          "0008 Wartortle - Hotel Doodle.jpg",
                          "0009 Blastoise - Akira Toriyama Sketch.jpg",
                          "0010 Caterpie - Diary of a Wimpy Kid.jpg",
                          "0011 Metapod - Jim Jinkins (Doug).jpg",
                          "0012 Butterfree BOBBY - King of the Hill (Mike Judge and Greg Daniels).jpg",
                          "0013 Weedle - Wplace.JPG",
                          "0014 Kakuna - Bochi Freakout.gif",
                          "0015 Beedrill - Early Simpsons Screenshot.jpg",
                          "0016 Pidgey - Ernest H. Shepard (classic winnie the pooh).jpg",
                          "0017 Pidgeotto - Emma Carlisle.jpg",
                          "0018 Pidgeot - 8 min CHALLENGE.jpg",
                          "0019 Rattata - Abstract Grunge.jpg",
                          "0020 Raticate - inspired by RET.jpg",
                          "0021 Spearow - Hunter x Hunter (Yoshihiro Togashi).jpg",
                          "0022 FEAROW - WIGGLYPAINT.gif",
                          "0023 Ekans - left-Handed CHALLENGE.jpg",
                          "0024 Arbok - Wojak.jpg",
                          "0025 Pikachu - Fat Albert.jpg",
                          "0026 Raichu - Ub Iwerks (classic Mickey Mouse).jpg",
                          "0027 Sandshrew - Heathcliff (Peter Gallagher).jpg",
                          "0028 Sandslash - Anthony Schepperd.jpg",
                          "0029 Nidoran F - Super Mario World sprite.jpg",
                          "0030 Nidorina - Gris Grimly.jpg",
                          "0031 Nidoqueen - Standard Playing Card.jpg",
                          "0032 Nidoran M - JayTheDevGuy.jpg",
                          "0033 Nidorino - The Flintstones.jpg",
                          "0034 Nidoking - Monochromatic Godzilla Poster (Pedro Demetriou).jpg",
                          "0035 Clefairy - 15 min CHALLENGE.jpg",
                          "0036 Clefable - Over The Garden Wall.jpg",
                          "0037 Vulpix - ime44.jpg",
                          "0038 Ninetails -  Afro Samurai (Takashi Okazaki).jpg",
                          "0039 Jigglypuff - Johnny the Homicidal Maniac (Jhonen Vasquez).jpg",
                          "0040 Wigglytuff - Al Jaffee (from Mad Magazine).jpg",
                          "0041 Zubat - Michel Canetti.jpg",
                          "0042 Golbat - FrankenFran (Katsuhisa Kigitsu).jpg",
                          "0043 Oddish - Plushie.jpg",
                          "0044 Gloom - Splatoon Promotional Art (Seita Inoue).jpg",
                          "0045 Vileplume - Peppa Pig.jpg",
                          "0046 Paras - 1 minute CHALLENGE.jpg",
                          "0047 Parasect - Gonzossm.jpg",
                          "0048 Venonat - fuzz.jpg",
                          "0049 Venomoth - Hollow Knight (Ari Gibson).jpg",
                          "0050 Diglett - Enigma of Amigara Fault (Junji Ito).jpg",
                          "0051 Dugtrio - smash remix.jpg",
                          "0052 Meowth - Garfield (Jim Davis).jpg",
                          "0053 Persian - Nichijou.jpg",
                          "0054 Psyduck - propaganda poster.jpg",
                          "0055 Golduck - shitty Mike Mosedale comic.jpg",
                          "0056 Mankey - Jack Stauber (2D drawn style).jpg",
                          "0057 Primeape - Yoshi\u0027s Island (Shigefumi Hino).jpg",
                          "0058 Growlith - Paranoid Android (Radiohead MV).jpg",
                          "0059 Arcanine - Digimon.jpg",
                          "0060 Polywag - 6 min CHALLENGE.jpg",
                          "0061 Polywhirl - Minimalist Graphic Design.jpg",
                          "0062 Poliwrath - blue marker on blue sticky note drawn poorly.jpg",
                          "0063 Abra - Harold Hutchins (the in-universe Captain Underpants comics).jpg",
                          "0064 Kadabra - non-specific minimalist two-tone style.jpg",
                          "0066 Machop - Caillou (Hélène Desputeaux).jpg",
                          "0067 Machoke - Mary\u0027s Coulerer brush.jpg",
                          "0068 Machamp - stick figure pen doodle.jpg",
                          "0069 Bellsprout - Fate visual novel (Takashi Takeuchi).jpg",
                          "0070 weepinbell - POG plant photobash.jpg",
                          "0071 Victreebel - doodle in sharpie and highlighter on red paper.jpg",
                          "0072 Tentacool - Mark beyer.jpg",
                          "0073 Tentacruel - 1 dollar notebook black pen doodle.jpg",
                          "0074 Geodude - coloured pencil in the RACCOON BOOK.JPG",
                          "0075 Graveler - in shitty pen in my tiny pocket sketchbook.jpg",
                          "0076 Golem - impressionist breadclip.jpg",
                          "0077 Ponyta - Sergio Aragones.jpg",
                          "0078 Rapidash - GREEN (coloured pencils and marker).jpg",
                          "0079 Slowpoke - napkin doodle.jpg",
                          "0080 Slowbro - carved into my desk.jpg",
                          "0081 Magnemite - doodlesd on yellow sticky in fat pencil.jpg",
                          "0082 Magneton - drawn in ink pen on a translucent purple sticky note.jpg",
                          "0083 Farfetch\u0027d - doodled in sharpie on my script notebook.jpg",
                          "0084 Doduo - Steins Gate VN (Ryohei Fuke).jpg",
                          "0085 Dotrio - drawn strangely with the QUAD-PEN.jpg",
                          "0086 Seel - sticky tak spinning.gif",
                          "0087 Dewgong - silly doodle black ink on blue paper.jpg",
                          "0088 Grimer - thin sharpie on orange paper.jpg",
                          "0089 Muk - doodled with 8B pencil.jpg",
                          "0090 Shellder - blue pen on green paper.jpg",
                          "0091 Cloyster - scrawled on the wildly out-of-touch texting abbreviations page of my schools day planner.jpg",
                          "0092 Gastly - idk freakish thing.jpg",
                          "0093 Haunter - sharpie blue sticky note cut-out.jpg",
                          "0094 Gengar - Tim Burton Sketch.jpg",
                          "0095 Onyx - Pumpkin Carving.jpg",
                          "0096 Drowzee - shitty-ass white sticky note black sharpy doodle on HALLOWEEN.jpg",
                          "0097 Hypno - creepy dark art.jpg",
                          "0098 Krabby - Rariatoo.jpg",
                          "0099 Kingler - yellow sticky shiny silver marker and black pen.jpg",
                          "0100 Voltorb - PEN ON MY OWN SKIN.jpg",
                          "0101 Electrode - Wigglypaint BOOM.gif",
                          "0102 Exeggcute - pink sticky note black pen pencil crayon.jpg",
                          "0103 Exeggutor - blach brush pen on translucent green sticky note.jpg",
                          "0104 Cubone - DRUNKEN Family Guy.jpg",
                          "0105 Marrowack - doodled in pencil on shitty branded sticky note.jpg",
                          "0106 hitmonlee - doodled on phone with pastel briushes.jpg",
                          "0107 Hitmonchan - bootleg bart shirt operation desert storm.jpg",
                          "0108 Likitung - black sharpie on orange paper mostly from memory.jpg",
                          "0109 Koffing - dots and swirly brushes.jpg",
                          "0110 Weezing - Jon Carpenter\u0027s The Thing.jpg",
                          "0111 Rhyhorn - 111 second CHALLENGE hard-drive brush.jpg",
                          "0112 Rhydon - tinfoil banana hammock.jpg",
                          "0113 Chansey - funny brush neon big chungus inspired piece.jpg",
                          "0114 Tangela - black marker pen \u0026 lazy pencil crayon colouring on greenish paper.jpg",
                          "0116 horsea - weird doodle on phone.jpg",
                          "0117 seadra - shitty doodle on a tiny orange sticky note.jpg",
                          "0118 Goldeen - shitty frieren fanart looking upward.jpg",
                          "0119 Seaking - bad microsoft paint doodle crayon brush.jpg",
                          "0120 Staryu - just fuckin around with filters and stuff.jpg",
                          "0121 Starmi - doodle pile on a tiny pink sticky note.jpg",
                          "0122 Mr Mime - Balatro joker card.jpg",
                          "0123 Scyther - rebelle shitty virtual watercolour.JPG",
                          "0124 Jynx - linepal.JPG",
                          "0125 Electabuzz - SHAKE ART.gif",
                          "0126 Magmar - Useless Painter clownarrhia.JPG",
                          "0127 Pinsir - Vpaint tamagachi loop.gif",
                          "0128 Tauros - Guernica Picasso inspired.jpg",
                          "0129 Magikarp - 1 munite 29 secondish CHALLENGE with the Swift brush CSP.jpg",
                          "0130 Gyarados - wii play fish ALL GEN 1 FISH.jpg",
                          "0131 Lapras - SHRIMP BRUSH.jpg",
                          "0132 Ditto - normal and shiny cut out of sticky notes with thin sharpie.jpg",
                          "0133 Eevee - idk weird colour swap thingy.jpg",
                          "0134 Vaporeon - fih shirt meme edit.jpg",
                          "0135 Jolteon - pop cat.gif",
                          "0136 Flareon - loops cat.jpg",
                          "0137 Porygon - MS PAINT.jpg",
                          "0138 Omanyte - THE PAINTER by SEGARIO.JPG",
                          "0139 Omastar - Squidbillies.jpg",
                          "0140 Kabuto - shitty dry erase board.jpg",
                          "0141 Kabutops - Kleki squares.JPG",
                          "0142 Aerodactyl - dark mode Doodle Pad browser program.JPG",
                          "0143 Snorlax - tldraw browser program sketch.JPG",
                          "0144 Articuno - Silk browser program.jpg",
                          "0145 Zapdos - polyline tool and paint bucket.jpg",
                          "0146 Moltres - Turkry jpg challenge.jpg",
                          "0147 Dratini - multicoloured pencil on white paper.jpg",
                          "0148 Dragonair - scribbonius.JPG",
                          "0149 Dragonite - 5 min 55 sec challenge.jpg",
                          "0150 Mewtwo - shitty silver and gold sticky note dooodle.jpg",
                          "0151A missingno normal - loose pixel art thing.jpg",
                          "0151B missingno ghost - felt tip marker 1 brush.jpg",
                          "0151C missingno arodacktyl - white fuzzy pen (csp brush) sketch.jpg",
                          "0151D missingno kabutops - blueish sketch thing.jpg",
                          "0151E missingno yellow - weird sketchy eldritch thing idk.jpg",
                          "0151F NEW YEARS EVE clove, rich and bartleby - strange femboy hooters cosplayers i guess.jpg",
                          "0152 Chikorita - fake stone carving.jpg",
                          "0153 Bayleef - Krazy Kat (George Harriman).jpg",
                          "0154 Meganium - Fred The Undead.jpg",
                          "0155 Cyndaquil - BIRTHDAY DOODLE.jpg",
                          "0157 Typhlosion - highlighter and marker cafeteria doodle.jpg",
                          "0158 Totodile - Abstract Shapes for Ian.jpg",
                          "0159 Croconaw - doodled as a Banjo-Kazooie enemy.jpg",
                          "0161 Sentret - NellHOJ comic.jpg",
                          "0162 Furret - Shards brush.jpg",
                          "0163 hoothoot - pixel sketch by Minute.JPG",
                          "0164 Noctowl - black sharpie scene on yellow sticky note.jpg",
                          "0165 Ledyba - sharpie on a cardboard box.jpg",
                          "0166 Ledian - Kamen Rider charactor swap.jpg",
                          "0167 Spinarak - family photo csp unsure pen.jpg",
                          "0168 Ariados - Hollow Knight GEN 2.jpg",
                          "0169 Crobat - Broad pencil CSP brush.jpg",
                          "0170 Chinchou - animated Meouw Studio.gif",
                          "0171 Lanturn - Wii Play Fishing GEN 2.jpg",
                          "0172 pichu - 40 x 40 pixels.JPG",
                          "0173 Cleffa - Meat Stick CSP brush.jpg",
                          "0174 Igglybuff - toe-beast done with fish-themed CSP brushes.jpg",
                          "0175 Togepi - lazy collage.jpg",
                          "0176 Togetic - weird pen CSP brush.jpg",
                          "0177 Natu - realistic eye on a blocky cartoon body.jpg",
                          "0178 Xatu - modular sticky notes crayon.jpg",
                          "0179 Mareep - sponge and oil CSP brushes.jpg",
                          "0180 Flaafy - photoshopped graphitti.jpg",
                          "0181 Ampharos - as a Raptorial Wyvern from Monster Hunter.jpg",
                          "0182 Bellossom - Autism Creature GIF.gif",
                          "0183 Marill - magma pallet challenge 1.JPG",
                          "0184 Azumarill - thin sharpie on mcdonalds fry box.jpg",
                          "0185 Sudowoodo - Tate Paint.JPG",
                          "0186 Politoed - csp Slice Of Graphitti brush.jpg",
                          "0187 Hoppip - Loose Contrl brush in 187 secondsish.jpg",
                          "0188 Skiploom - csp Fadey Pen.jpg",
                          "0189 Jumpluff - csp Tape Pen.jpg",
                          "0190 Aipom - Animal Crossing gc monkey villager.jpg",
                          "0192 Sunflora - bathroom stall graffiti.jpg",
                          "0193 Yanma - squished.jpg",
                          "0194 Wooper - Red Ball flashgame.jpg",
                          "0195 Quagsire - Inky Pen csp monochromatic scene.jpg",
                          "0196 Espeon - thick couloured lineart James the Cat.jpg",
                          "0197 Umbreon - Spaghetti Cat frightening photoshop.jpg",
                          "0198 Murkrow - FAT PENCIL on dotted paper.jpg",
                          "0199 Slowking - simpsons-ish.jpg",
                          "0200 Misdreavus - extra fine marker pen on a yellow sticky in the back of a moving car.jpg",
                          "0201 Unown - CRUNCH pen csp RAMEN SPLOOSH.jpg",
                          "0202 Wobbuffet - 100% OJ.jpg",
                          "0203 Girafarig - red pixel pen MAGMA.JPG",
                          "0204 Pineco - pinecone photobash + cartoon eyes.jpg",
                          "0205 Forretress - cut from fancy paper.jpg",
                          "0206 Dunsparce - green pen on lined paper.jpg",
                          "0207 Gligar - Hello Kittyy.jpg",
                          "0208 Steelix - edited into Smiling Friends.jpg",
                          "0209 Snubbull - WET FLOOR sign.jpg",
                          "0210 Granbull - GIMKIT.JPG",
                          "0211 Qwilifish - Dooble (Two More Eggs).jpg",
                          "0212 Scizor - The Amazing World of Gumball.jpg",
                          "0213 Shuckle - flipbook GIF.gif",
                          "0214 Heracross - GROBIX.jpg",
                          "0215 Sneasel - BIG PENCIL ENERGY csp brush.jpg",
                          "0216 Teddiursa - David Firth traditional style.jpg",
                          "0217 Ursaluna - Danny Phantom.jpg",
                          "0218 Slugma - BeetleMoses comic.jpg",
                          "0219 magcargo - Medieval snail vs knight book art.jpg",
                          "0220 Swinub - Stuck In The Sound LETS GO.jpg",
                          "0221 Swinub - side pencil sketch.jpg",
                          "0222 Corsola - March Comes Like a Lion cover (Chica Umino).jpg",
                          "0223 Remoraid - Stromatolite Pen 20 min challenge CSP.jpg",
                          "0224 Octillery - pencil crayon kitty book AIRBNB.jpg",
                          "0225 Delibird - poorly coloured-in vintage christmas colouring-book page.jpg",
                          "0226 Mantine - linesless texture slap.jpg",
                          "0227 Skarmony - weird sharp style idk.jpg",
                          "0228 Houndour - SHITTY PEN AND PENCIL IN CLENCHED FIST OF RAGE.jpg",
                          "0229 Houndoom - drawn on my short film script in Adobe Acrobat.JPG",
                          "0230 Kingdra - Khruangbin \u0026 Leon Bridges Chocolate Hills MV.jpg",
                          "0231 Phanpy - Golfinho Yurii.jpg",
                          "0232 Donphan - dying sharpie and crayon.jpg",
                          "0233 Porygon2 - shitty blender model.JPG",
                          "0234 Stantler - weird neon brush thing.jpg",
                          "0235 Smeargle - circular frame single line abstract marker doodle.jpg",
                          "0236 Tyrogue - teeny tiny widdle mult-colour pen doodle.jpg",
                          "0237 Hitmontop - Tomodachi Life demo.jpg",
                          "0238 Smoochum - white sticky note highlighter and marker.jpg",
                          "0239 Elekid - paper doll thingy.jpg",
                          "0240 Magby - stickers.jpg",
                          "0241 Miltank - stairwell graffiti.jpg",
                          "0242 Blissey - weird bullshit idk.jpg",
                          "0243 Raikou - CSP Odd ink.jpg",
                          "0244 Entai - old japanese newspaper in red sharpie.jpg",
                          "0245 Suicune - drawn in sharpie and highlighter sloppily with my fist.jpg",
                          "0246 Larvitar - pencil and coloured pen mini cut-out.jpg",
                          "0247 Pupitar - weird phone doodle.jpg",
                          "0248 Tyranitar - green blotchy thing.jpg",
                          "0249 Lugia - partilly cutout pencil doodle.jpg",
                          "0250 Ho-Oh - whiteboard wormseye view.jpg",
                          "0251 Celebi - Salvador Dali inspired.jpg",
                          "0251A Papyō - little green sticky note sharpie.jpg",
                          "0251B Kabīn - TEENY TINY thin pen on paper scrap.jpg",
                          "0251C Bararina - Babybel wax.jpg",
                          "0251D Monja \u0026 Jaranra - navy blue sharpie on a bamboo box.jpg",
                          "0251E Honoguma, Volbear and Dynabear - Cas Van De Pol.jpg",
                          "0251F Namēru - scrap paper sharpie highlighter.jpg",
                          "0251G Mikon - Succulent Noise CSP.jpg",
                          "0251H Rīfi - crusty pencil and soda fizz.jpg",
                          "0251I Kurusu, Aqua \u0026 Aquaria - light blue pen on small paper scrap.jpg",
                          "0252 Treecko - willow charcoal on tree bark.jpg",
                          "0253 Grovyle - Mummy Joe.jpg",
                          "0254 Sceptile - NerdLand.jpg",
                          "0255 Torchic - FIRE AND ASH.jpg",
                          "0256 Combusken - Hazen Becker.jpg",
                          "0257 Blaziken - simple tri-colour sprite.jpg",
                          "0258 Mudkip - water and charcoal dust.jpg",
                          "0259 Marshtomp - Tracy Ullman show simpsons shorts.jpg",
                          "0260 Swampert - Paper\u0027s Please Lucas Pope.jpg",
                          "0261 Poochyena - The Dog collection.jpg",
                          "0262 Mightyena - weird sketchy thing.jpg",
                          "0263 Zigzagoon - line tool.jpg",
                          "0264 Linoone - 1D image.jpg",
                          "0265 Wurmple - pointilism brush neon.jpg",
                          "0266 Silcoon - paper scraps.jpg",
                          "0267 Beautifly - white sharpie paint pen on a black box.jpg",
                          "0268 Cascoon - sponge brush and realistic eye.jpg",
                          "0270 Lotad - Shel Silverstein.jpg",
                          "0271 Lombre - cunty reaction pic.jpg",
                          "0272 Ludicolo - Absolute Batman.jpg",
                          "0273 Seedot - Megaman sprite.JPG",
                          "0274 Nuzleaf - lazy John Locke from LOST photobash.jpg",
                          "0275 Shiftry - Walt Kelly (Pogo).jpg",
                          "0276 Taillow - scary face brush.jpg",
                          "0277 Swellow - Super Mario Land 2.JPG",
                          "0278 Wingull - floppy thing.gif",
                          "0279 Pelipper - pleasant CSP pencil brushes.jpg",
                          "0280 Ralts - block deco brush.jpg",
                          "0281 Kirlia - cutup elastic bands.jpg",
                          "0282 Gardevoir - coffin of andy and leyley.jpg",
                          "0283 Surskit - chiikawa.jpg",
                          "0284 Masquerain - CSP 7 min textured pen.jpg",
                          "0285 Shroomish - made from letters typed in Bobycaygeon BRK font.jpg",
                          "0286 Breloom - tron-ish doodle.jpg",
                          "0287 Slakoth - flat crunchy III calligraphy brush csp.jpg",
                          "0288 Vigoroth - eraser red backgronf CSP.jpg",
                          "0289 Slaking - werid chunky style, large spray brush.jpg",
                          "0291 Ninjask - black pen on the margins of a monologue contest score card.jpg",
                          "0292 Shedinja - sick-ass pastel brush design.jpg",
                          "0293 Whismur - sloppy marker brush csp.jpg",
                          "0294 Loudred - polyline tool thing.jpg",
                          "0295 Exploud - ripped paper and sharpie on convocation day.jpg",
                          "0296 Makuhita - drawn with half tone dots.jpg",
                          "0297 Hariyama - path pen CSP.jpg",
                          "0298 Azurill - fruitiger aero.jpg",
                          "0299 Nosepass - unfinished fantasy-ish sketch.jpg",
                          "0300 Skitty - small drawing done with mouse.jpg",
                          "0301 Delcatty - Top Cat (hanna-barbera).jpg",
                          "0302 Sableye - felt tip pen brush.jpg",
                          "0303 Mawile - grease pencil brush.jpg",
                          "0304 Aron - jason cosplay priest pencil brush.jpg",
                          "0305 Lairon - blueberry pen on my old childhood door.jpg",
                          "0306 Aggron - Thompson texture pen.jpg",
                          "0307 Meditite - giger brush csp.jpg",
                          "0308 Medicham - Tim Sale.jpg",
                          "0309 Electrike - Mr Beast logo.jpg",
                          "0310 Manectric - funny faces brush.jpg",
                          "0311-0312 Plusle \u0026 Minun - squidge pen.jpg"
                      ],
    "graphic-design":  [
                           "2018 season poster.JPG",
                           "2019 ramensploosh logo.png",
                           "2019 ramensploosh logo2.png",
                           "2019 season poster copy3.png",
                           "2020 season poster finale.jpg",
                           "black shirt.jpg",
                           "BOO PARK.png",
                           "Card Board Game Night logo - circle colour fill.png",
                           "FINAL 2021 POSTER DESIGN.png",
                           "health bloom.jpg",
                           "improv 101 last1.jpg",
                           "JOSHI PARK.png",
                           "logo ideas.jpg",
                           "MOTHEW transparent.png",
                           "old logo 1.png",
                           "old logo 2.png",
                           "old logo 3.png",
                           "old logo 4.png",
                           "old logo 5.png",
                           "old logo 6.png",
                           "old logo 7.png",
                           "old logo 8.png",
                           "old logo 9.png",
                           "PIKMIN SUMMER CAMP.png",
                           "purple ammonite left1.jpg",
                           "purple ammonite left2.jpg",
                           "purple ammonite mid1.jpg",
                           "purple ammonite mid2.jpg",
                           "ramensploosh prof pic 2019.jpg",
                           "ramensploosh06.jpg",
                           "ramensploosh07.jpg",
                           "ramensploosh08 copy.jpg",
                           "shadowbox.jpg",
                           "shatters amiibo banner drop shadow2.png",
                           "SUPER MARIO WORLDERS 2SERS.png",
                           "SUPER PETEY BROS JR.png",
                           "twitch banner bw.png",
                           "twitter banner copy.jpg",
                           "Untitled-3.jpg"
                       ],
    "illustration":  [
                         "30531367_1802750223120534_3283928296554758144_o.jpg",
                         "aipom squad.jpg",
                         "alley crab.jpg",
                         "bard.png",
                         "BARTLEBY2.png",
                         "bloodborb.jpg",
                         "Carrion Release 2.jpg",
                         "chowder ret.png",
                         "christmas hand2.jpg",
                         "clemstache.png",
                         "CLOVE2.png",
                         "collective 01.jpg",
                         "ded ret.jpg",
                         "doomscroller.png",
                         "ENA FISH render.png",
                         "femtanyl fanart.jpg",
                         "flayer sketch 1.jpg",
                         "freaky fish-man.JPG",
                         "highway man pillowman copy.jpg",
                         "I splash page.jpg",
                         "IMG_20191020_170932.jpg",
                         "it me.jpg",
                         "janitor.png",
                         "jester.png",
                         "jinx 1.jpg",
                         "khezu.jpg",
                         "kidpix-1731465112710.png",
                         "leg demon.jpg",
                         "MG J custom copy.jpg",
                         "monster girl 01.1.jpg",
                         "my one amoung us fanart.png",
                         "narcoleptic.png",
                         "nasty man.gif",
                         "nerd.png",
                         "night demon 01.jpg",
                         "oneyplays one wing remix art BIG.jpg",
                         "onion error copyyy.jpg",
                         "pikmeen.jpg",
                         "pillar guy.jpg",
                         "pillow man close-up.jpg",
                         "pillow man core concept.jpg",
                         "polteageist.jpg",
                         "princess.png",
                         "R splash page.jpg",
                         "random stylized monster girl.jpg",
                         "rat creature.jpg",
                         "ret.jpg",
                         "rich clove and bartleby.jpg",
                         "RICH2.png",
                         "Salli.jpg",
                         "screm.jpg",
                         "spooky.png",
                         "swolemato.jpg",
                         "The Last HappyMeal FINAL.jpg",
                         "The Last HappyMeal FINAL.png",
                         "unDED RET.jpg",
                         "XUNJAI DESPAIR.png",
                         "XUNJAI JOY.png",
                         "zommin blue.png",
                         "zommin flying.png",
                         "zommin purple.png",
                         "zommin red.png",
                         "zommin rock.png",
                         "zommin white.png",
                         "zommin yellow.png"
                     ],
    "new-fortune":  [
                        "Capture.JPG",
                        "comparisson 1.jpg",
                        "comparisson 2.jpg",
                        "fav mushlogos.jpg",
                        "flo.JPG",
                        "flo2.JPG",
                        "flo3.JPG",
                        "flo4.JPG",
                        "flowers and leaves.png",
                        "flowers and leaves2.png",
                        "improv copy.jpg",
                        "improv.jpg",
                        "LOGO BROWN 1.png",
                        "LOGO BROWN 2.png",
                        "LOGO EXPERIMENTS 1.jpg",
                        "LOGO EXPERIMENTS 2.jpg",
                        "LOGO EXPERIMENTS 3.jpg",
                        "LOGO EXPERIMENTS 4.jpg",
                        "logoo.jpg",
                        "logooo.jpg",
                        "logoooo.jpg",
                        "NEW logo dark green 2.png",
                        "personal fave i think.png",
                        "piiiiik.JPG",
                        "piiik.JPG",
                        "pikhack blowhogs 1.jpg",
                        "pikhack blowhogs 2.jpg",
                        "pikhack blowhogs 3.jpg",
                        "pikmin b1.png",
                        "pikmin b2.png",
                        "pikmin new fortune logo draft 1.jpg",
                        "pikmin new.png",
                        "PIKMIN no shadow.png",
                        "PIKMIN no shadow2.png",
                        "PIKMIN shadow.png",
                        "PIKMIN shadow2.png",
                        "simple ship.jpg",
                        "snagret 01.jpg",
                        "so many.JPG",
                        "subtitle.jpg",
                        "the ship 01.jpg",
                        "the ship 02.jpg",
                        "unknown (1).png",
                        "unknown (2).png",
                        "unknown (3).png",
                        "unknown.png"
                    ],
    "other":  [
                  "20210404_000329.jpg",
                  "20210404_000331.jpg",
                  "20210404_001058.jpg",
                  "20251120_195817.jpg",
                  "heath comission.jpg",
                  "IMG_20180301_083846_034.jpg",
                  "spooky kieran prof pic.jpg"
              ],
    "photography":  [
                        "05.jpg",
                        "30.jpg",
                        "40.JPG",
                        "41.JPG",
                        "BEYOND PHOTOS 1.jpg",
                        "BEYOND PHOTOS 2.jpg",
                        "BEYOND PHOTOS.jpg",
                        "hand.jpg",
                        "hhhhhhhhhhhhjjjjjj.jpg",
                        "hhhhhhj.jpg",
                        "hhhhjjjjjjjhhhhhj.jpg",
                        "hhjjhjjhjhj.jpg",
                        "hjhhhjhhjh.jpg",
                        "hjhjhjhj.jpg",
                        "hjjhhhhhhhhhhhhhh.jpg",
                        "hjjhjhhhhh.jpg",
                        "hjjhjhjhjhhjhj.jpg",
                        "hjjhjjhjhjh.jpg",
                        "hjjjhhjjjjjjj.jpg",
                        "hjjjhjhjh.jpg",
                        "hjjjjjjjhhhhhhhj.jpg",
                        "hjjjjjjjjjjjjjh.jpg",
                        "IMG_4502.JPG",
                        "IMG_4587.JPG",
                        "IMG_4606.JPG",
                        "IMG_4739.JPG",
                        "IMG_8342.JPG",
                        "IMG_9156 copy.jpg",
                        "orange promo 3 coopy.jpg"
                    ],
    "zines":  [
                  "10 and 11.png",
                  "12.png",
                  "13.png",
                  "14.png",
                  "15.png",
                  "16.png",
                  "17.png",
                  "1A.jpg",
                  "1B.jpg",
                  "2A.jpg",
                  "2B.jpg",
                  "3.png",
                  "3A.jpg",
                  "3B.jpg",
                  "4.png",
                  "5.png",
                  "6.png",
                  "7.png",
                  "8.png",
                  "9.png",
                  "COVER.png"
              ]
};

